return {
	theme = {
		palette = {
			background = "#1a1b26",
			foreground = "#c0caf5",
			selection = "#283457",
			cursor = "#c0caf5",
			link = "#2ac3de",
			line_number = "#545c7e",
			line_number_bg = "#16161e",
			current_line = "#292e42",
			ui_bar_bg = "#16161e",
			ui_panel_bg = "#16161e",
			ui_panel_overlay = "#16161eeb",
			ui_hover = "#292e42",
			ui_pressed = "#394b70",
			ui_tab_inactive_bg = "#1a1b26",
			ui_accent = "#7aa2f7",
			ui_border = "#15161e",
			ui_modified = "#e0af68",
			ui_text = "#c0caf5",
			ui_text_inactive = "#a9b1d6",
			color0 = "#15161e",
			color1 = "#f7768e",
			color2 = "#9ece6a",
			color3 = "#e0af68",
			color4 = "#7aa2f7",
			color5 = "#bb9af7",
			color6 = "#7dcfff",
			color7 = "#a9b1d6",
			color8 = "#414868",
			color9 = "#ff899d",
			color10 = "#9fe044",
			color11 = "#faba4a",
			color12 = "#8db0ff",
			color13 = "#c7a9ff",
			color14 = "#a4daff",
			color15 = "#c0caf5",
		},
		syntax = {
			comment = "#565f89",
			string = "#9ece6a",
			keyword = "#9d7cd8",
			number = "#ff9e64",
			["function"] = "#7aa2f7",
			variable = "#c0caf5",
			type_name = "#2ac3de",
			operator = "#89ddff",
			builtin = "#7dcfff",
			punctuation = "#89ddff",
			constant = "#ff9e64",
			attribute = "#7dcfff",
			namespace = "#7aa2f7",
			label = "#7aa2f7",
			error = "#db4b4b",
			preproc = "#7dcfff",
			macro = "#7dcfff",
			escape = "#ff9e64",
			keyword_control = "#9d7cd8",
			function_method = "#7aa2f7",
			type_builtin = "#27a1b9",
		},
	},

	editor = {
		theme = {
			palette = {
				background = "#1a1b26",
				foreground = "#c0caf5",
				selection = "#283457",
				current_line = "#292e42",
				line_number = "#545c7e",
				line_number_bg = "#16161e",
				cursor = "#c0caf5",
				link = "#2ac3de",
			},
			syntax = {
				comment = "#565f89",
				string = "#9ece6a",
				keyword = "#9d7cd8",
				number = "#ff9e64",
				["function"] = "#7aa2f7",
				variable = "#c0caf5",
				type_name = "#2ac3de",
				operator = "#89ddff",
				builtin = "#7dcfff",
				punctuation = "#89ddff",
				constant = "#ff9e64",
				attribute = "#7dcfff",
				namespace = "#7aa2f7",
				label = "#7aa2f7",
				error = "#db4b4b",
				preproc = "#7dcfff",
				macro = "#7dcfff",
				escape = "#ff9e64",
				keyword_control = "#9d7cd8",
				function_method = "#7aa2f7",
				type_builtin = "#27a1b9",
			},
			groups = {
				Normal = { fg = "#c0caf5", bg = "#1a1b26" },
				NormalFloat = { fg = "#c0caf5", bg = "#16161e" },
				Comment = { fg = "#565f89", italic = true },
				Keyword = { fg = "#9d7cd8", italic = true },
				String = "#9ece6a",
				Number = "#ff9e64",
				Function = "#7aa2f7",
				Identifier = "#bb9af7",
				Type = "#2ac3de",
				Operator = "#89ddff",
				Constant = "#ff9e64",
				Special = "#7dcfff",
				PreProc = "#7dcfff",
				Delimiter = "#89ddff",
				Label = "#7aa2f7",
				Error = "#db4b4b",
				LineNr = "#545c7e",
				CursorLine = { bg = "#292e42" },
				CursorLineNr = { fg = "#ff9e64", bold = true },
				Visual = { bg = "#283457" },
				Search = { fg = "#c0caf5", bg = "#3d59a1" },
				IncSearch = { fg = "#15161e", bg = "#ff9e64" },
				MatchParen = { fg = "#ff9e64", bold = true },
				ErrorMsg = "#db4b4b",
				WarningMsg = "#e0af68",
				DiagnosticError = "#db4b4b",
				DiagnosticWarn = "#e0af68",
				DiagnosticInfo = "#0db9d7",
				DiagnosticHint = "#1abc9c",
				DiagnosticUnderlineError = { sp = "#db4b4b", undercurl = true },
				DiagnosticUnderlineWarn = { sp = "#e0af68", undercurl = true },
				DiagnosticUnderlineInfo = { sp = "#0db9d7", undercurl = true },
				DiagnosticUnderlineHint = { sp = "#1abc9c", undercurl = true },
			},
			captures = {
				["@comment"] = "#565f89",
				["@comment.error"] = "#db4b4b",
				["@comment.warning"] = "#e0af68",
				["@comment.info"] = "#0db9d7",
				["@comment.note"] = "#1abc9c",
				["@comment.todo"] = "#7aa2f7",
				["@constant"] = "#ff9e64",
				["@constructor"] = "#bb9af7",
				["@function"] = "#7aa2f7",
				["@function.method"] = "#7aa2f7",
				["@keyword"] = { fg = "#9d7cd8", italic = true },
				["@keyword.function"] = "#bb9af7",
				["@label"] = "#7aa2f7",
				["@number"] = "#ff9e64",
				["@operator"] = "#89ddff",
				["@punctuation.bracket"] = "#89ddff",
				["@punctuation.delimiter"] = "#89ddff",
				["@string"] = "#9ece6a",
				["@string.escape"] = "#ff9e64",
				["@string.special.url"] = "#2ac3de",
				["@type"] = "#2ac3de",
				["@type.builtin"] = "#27a1b9",
				["@variable"] = "#c0caf5",
				["@variable.builtin"] = "#7dcfff",
				["@markup.emphasis"] = { italic = true },
				["@markup.strong"] = { bold = true },
				["@markup.strikethrough"] = { strikethrough = true },
				["@markup.underline"] = { underline = true },
				["@markup.link.url"] = "#2ac3de",
			},
			links = {
				["@function.call"] = "@function",
				["@function.method.call"] = "@function.method",
				["@keyword.return"] = "@keyword",
				["@keyword.coroutine"] = "@keyword",
				["@keyword.operator"] = "@operator",
				["@attribute"] = "PreProc",
				["@annotation"] = "PreProc",
				["@boolean"] = "Constant",
			},
		},
	},
}
