plugins {
    id 'com.android.application'
}

android {
    namespace 'dev.zide.androidhost'
    compileSdk 35
    buildToolsVersion '35.0.0'

    defaultConfig {
        applicationId 'dev.zide.androidhost'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.0.1'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
