const std = @import("std");

pub const PlatformCapability = struct {
    os_tag: std.Target.Os.Tag,
    host_contract: []const u8,
    app_host_shape: []const u8,
    render_host_shape: []const u8,
    current_runtime_graphics_path: []const u8,
    ffi_surface: []const u8,
    supports_fontconfig: bool,
    supports_terminal_bundle: bool,
    supports_windows_shell_extension: bool,
    uses_windows_gui_subsystem: bool,
    supports_windows_resources: bool,
    fontconfig_include_dir: ?[]const u8,
    needs_system_zlib: bool,
    common_graphics_system_libs: []const []const u8,
    common_graphics_frameworks: []const []const u8,
    ffi_system_libs: []const []const u8,
    ffi_frameworks: []const []const u8,
    sdl_test_system_libs: []const []const u8,
    sdl_test_frameworks: []const []const u8,
};

pub const supported_platforms = [_]PlatformCapability{
    .{
        .os_tag = .linux,
        .host_contract = "SDL-managed desktop host under the shared native-host contract",
        .app_host_shape = "SDL desktop app lifecycle",
        .render_host_shape = "SDL window host; GL drawable path today",
        .current_runtime_graphics_path = "OpenGL via SDL3/system GL",
        .ffi_surface = "libc + pthread/dl/rt",
        .supports_fontconfig = true,
        .supports_terminal_bundle = true,
        .supports_windows_shell_extension = false,
        .uses_windows_gui_subsystem = false,
        .supports_windows_resources = false,
        .fontconfig_include_dir = "/usr/include/fontconfig",
        .needs_system_zlib = true,
        .common_graphics_system_libs = &.{ "GL", "m", "pthread", "dl", "rt" },
        .common_graphics_frameworks = &.{},
        .ffi_system_libs = &.{ "m", "pthread", "dl", "rt" },
        .ffi_frameworks = &.{},
        .sdl_test_system_libs = &.{"GL"},
        .sdl_test_frameworks = &.{},
    },
    .{
        .os_tag = .macos,
        .host_contract = "Cocoa/AppKit-native host contract via SDL bridge today",
        .app_host_shape = "AppKit application lifecycle",
        .render_host_shape = "Cocoa view host; Metal target, SDL/OpenGL runtime today",
        .current_runtime_graphics_path = "OpenGL framework via SDL3",
        .ffi_surface = "Cocoa framework",
        .supports_fontconfig = false,
        .supports_terminal_bundle = false,
        .supports_windows_shell_extension = false,
        .uses_windows_gui_subsystem = false,
        .supports_windows_resources = false,
        .fontconfig_include_dir = null,
        .needs_system_zlib = true,
        .common_graphics_system_libs = &.{},
        .common_graphics_frameworks = &.{ "OpenGL", "Cocoa", "IOKit", "CoreVideo" },
        .ffi_system_libs = &.{},
        .ffi_frameworks = &.{"Cocoa"},
        .sdl_test_system_libs = &.{},
        .sdl_test_frameworks = &.{"OpenGL"},
    },
    .{
        .os_tag = .windows,
        .host_contract = "SDL-managed desktop host with Windows-native install/shell pressure",
        .app_host_shape = "SDL desktop app lifecycle with Windows GUI subsystem",
        .render_host_shape = "SDL window host; OpenGL runtime today",
        .current_runtime_graphics_path = "OpenGL32 via SDL3",
        .ffi_surface = "user32/shell32",
        .supports_fontconfig = false,
        .supports_terminal_bundle = false,
        .supports_windows_shell_extension = true,
        .uses_windows_gui_subsystem = true,
        .supports_windows_resources = true,
        .fontconfig_include_dir = null,
        .needs_system_zlib = false,
        .common_graphics_system_libs = &.{ "opengl32", "gdi32", "comdlg32", "dwrite", "ole32", "winmm", "user32", "shell32" },
        .common_graphics_frameworks = &.{},
        .ffi_system_libs = &.{ "user32", "shell32" },
        .ffi_frameworks = &.{},
        .sdl_test_system_libs = &.{"opengl32"},
        .sdl_test_frameworks = &.{},
    },
};

pub fn platformCapability(os_tag: std.Target.Os.Tag) ?PlatformCapability {
    inline for (supported_platforms) |capability| {
        if (capability.os_tag == os_tag) return capability;
    }
    return null;
}
