#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/reference_repos/rendering/khronos_refpages_md"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

mkdir -p "$ROOT_DIR/EGL" "$ROOT_DIR/OpenGL"

download_md() {
  local url="$1"
  local out="$2"
  local html="$TMP_DIR/$(basename "$out" .md).html"
  echo "fetch $url -> $out"
  curl -L --fail --silent --show-error "$url" -o "$html"
  pandoc --from=html --to=gfm "$html" -o "$out"
}

EGL_DOCS=(
  "eglBindAPI https://registry.khronos.org/EGL/sdk/docs/man/html/eglBindAPI.xhtml"
  "eglChooseConfig https://registry.khronos.org/EGL/sdk/docs/man/html/eglChooseConfig.xhtml"
  "eglCreateWindowSurface https://registry.khronos.org/EGL/sdk/docs/man/html/eglCreateWindowSurface.xhtml"
  "eglQuerySurface https://registry.khronos.org/EGL/sdk/docs/man/html/eglQuerySurface.xhtml"
  "eglSurfaceAttrib https://registry.khronos.org/EGL/sdk/docs/man/html/eglSurfaceAttrib.xhtml"
  "eglSwapBuffers https://registry.khronos.org/EGL/sdk/docs/man/html/eglSwapBuffers.xhtml"
  "eglSwapInterval https://registry.khronos.org/EGL/sdk/docs/man/html/eglSwapInterval.xhtml"
)

OPENGL_DOCS=(
  "glBindFramebuffer https://registry.khronos.org/OpenGL-Refpages/gl4/html/glBindFramebuffer.xhtml"
  "glBlitFramebuffer https://registry.khronos.org/OpenGL-Refpages/gl4/html/glBlitFramebuffer.xhtml"
  "glDrawBuffer https://registry.khronos.org/OpenGL-Refpages/gl4/html/glDrawBuffer.xhtml"
  "glFinish https://registry.khronos.org/OpenGL-Refpages/gl4/html/glFinish.xhtml"
  "glFlush https://registry.khronos.org/OpenGL-Refpages/gl4/html/glFlush.xhtml"
  "glReadBuffer https://registry.khronos.org/OpenGL-Refpages/gl4/html/glReadBuffer.xhtml"
)

for entry in "${EGL_DOCS[@]}"; do
  name="${entry%% *}"
  url="${entry#* }"
  download_md "$url" "$ROOT_DIR/EGL/$name.md"
done

for entry in "${OPENGL_DOCS[@]}"; do
  name="${entry%% *}"
  url="${entry#* }"
  download_md "$url" "$ROOT_DIR/OpenGL/$name.md"
done

cat > "$ROOT_DIR/README.md" <<'EOF'
# Khronos Refpages Mirror

Curated local Markdown mirror of official Khronos EGL and OpenGL refpages for
the current Wayland/SDL/OpenGL presentation investigation.

Generated by:

`scripts/setup_khronos_refpages_md.sh`

Source families:

- `https://registry.khronos.org/EGL/sdk/docs/man/html/`
- `https://registry.khronos.org/OpenGL-Refpages/gl4/html/`
EOF

echo "done."
